### ISSUE TITLE
Feature Request: mincLogLikRatioParametricBootstrap parallelization

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/RMINC#170] opened 2017-08-31 14:30 UTC
On larger datasets this is a bit painful to use, would be great if this were parallelized like the mincLmer

**Comment by cfhammill** [comment] 2017-08-31 14:56
Duplicate of #25

**Closed by cfhammill** 2017-08-31 14:56 UTC

**Comment by gdevenyi** [comment] 2017-08-31 15:07
oops!
